### ISSUE TITLE
Allow token input from user on DIBS execution instead of hardcoded

### ISSUE THREAD

**Issue by Karpo22** [shadowedice/DIBS#6]
Right now the token value is hard coded into DIBS.  It would be nice if an input box could be executed at login to prompt the user to enter in a desired bot token.

**Comment by shadowedice** [comment]
I dont see this as an issue. Right now you can just simply modify your own Token.py file to include the correct token. This would require a person to enter a token every single time they try to start the bot making it more tedious.

**Comment by Karpo22** [comment]
I never said it would be hard-coded into the main DIBS file and run every single time.  It would be a different source file that the user can run called DIBS Setup, or whatever, that allows the user to input any preferences, save those preferences to the relevant source file, and then run DIBS.  I need practice on modifying source files from other files, and it would prevent users from having to modify source code directly as DIBS grows/expands.

**Comment by shadowedice** [comment]
> I never said it would be hard-coded into the main DIBS file and run every single time.
>  It would be nice if an input box could be executed at login to prompt the user to enter in a desired bot token.

This directly says that they would be prompted to insert the token each time at login. Also for preferences you don't normally change source code but modify a configuration file instead. If you are looking to make DIBS read a configuration file that fine. It is basically what Token.py currently is (notice how it isn't included in the repository because it is unique per person).

**Comment by Karpo22** [comment]
"could be be executed" as in not each time.  Creating a config/plist is what I was talking about.  Not sure why you keep closing this ticket...

**Comment by Karpo22** [comment]
Regardless of whether the ticket is open or closed, this is what I'm going to be working on.

**Comment by shadowedice** [comment]
I keep closing it because the title "Allow token input from user on DIBS execution instead of hardcoded" is not an issue or something that needs to be modified. The token value needs to be "hardcoded" somewhere either in a source file or in a configuration file. It does not make sense to prompt someone running the bot to enter their nearly 50 character token ID each time they run the application.

**Comment by Karpo22** [comment]
Right, I get that, I'm just saying that if we're working on DIBS as a collaborative project I would appreciate it if the tickets I open aren't just closed out because somebody else doesn't think it's viable.  If there's a problem with a ticket, and you think it should be closed, then all parties involved in the ticket should agree it needs to be closed.  In this case it was just a misunderstanding of what I was intending to do because I wrote the ticket late at night.  I am opening a new ticket to make my intentions more clear since this one has been bogged down

**Comment by shadowedice** [comment]
I had asked two other collaborators on their opinion on the ticket and they agreed that how it was originally proposed did not seem like something we needed or would want. The new ticket (#9) is much better and allows for expandibility.

**Comment by Karpo22** [comment]
https://www.youtube.com/watch?v=HZuhYJynSk8

Sounds good, from my perspective it just looked like it kept getting shut down with no warning/input.  Simple misunderstanding from both directions.  Carry on!
